name: build-wheels

on:
  push:
    branches: [master, develop, '**-test-release']

jobs:
  build-wheels-osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          # This is just the Python version to build the wheels
          python-version: 3.7
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: osx-wheel
          path: semgrep/dist.zip
  build-wheels-manylinux:
    runs-on: 'ubuntu-16.04'
    container: 'returntocorp/sgrep-build:ubuntu-16.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Python
        run: |
          rm /usr/bin/python
          ln `which python3.7` /usr/bin/python
      - name: Install zip & musl-tools
        run: apt-get update && apt install -y zip musl-tools
      - name: Build the wheels
        run: ./release-scripts/build-wheels.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manylinux-wheel
          path: semgrep/dist.zip
  test-wheels-manylinux:
    needs: ['build-wheels-manylinux']
    runs-on: 'ubuntu-16.04'
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: manylinux-wheel
          path: manylinux-wheel
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          # This is just the Python version to build the wheels
          python-version: 3.7
      - name: unzip dist
        run: unzip ./manylinux-wheel/dist.zip
      - name: install package
        run: /opt/python/cp36-cp36m/bin/pip install dist/*.whl
      - name: test package
        workdir: /opt/python/cp36-cp36m/bin/
        run: ./semgrep --version
      - name: test core
        run: semgrep-core --version
        workdir: /opt/python/cp36-cp36m/bin/
      - name: e2e test
        workdir: /opt/python/cp36-cp36m/bin/
        run: ./semgrep -l python readelf.py -e '$1 == $1'
