name: release-ubuntu

on:
  push:
    branches: [master, develop, '**-test-release']

jobs:
  release-ubuntu:
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04']
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Run Ubuntu build script
        run: ./release-scripts/ubuntu-release.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-${{ matrix.os }}-${{ github.sha }}
          path: artifacts.tar.gz
